force-app/main/default/objects/Cocktail_Ingredients__c/Cocktail_Ingredients__c.object-meta.xml
<CustomObject>
    <label>Cocktail Ingredient</label>
    <nameField>
        <label>Cocktail Ingredients Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cocktail Ingredients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cocktail_Ingredients__c/fields/Cocktail__c.field-meta.xml
<CustomField>
    <fullName>Cocktail__c</fullName>
    <label>Cocktail</label>
    <referenceTo>Coctail__c</referenceTo>
    <relationshipLabel>Cocktail Ingredients</relationshipLabel>
    <relationshipName>Cocktail_Ingredients</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cocktail_Ingredients__c/fields/Drink_Ing_External_Id__c.field-meta.xml
<CustomField>
    <fullName>Drink_Ing_External_Id__c</fullName>
    <externalId>true</externalId>
    <label>Drink_Ing_External_Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cocktail_Ingredients__c/fields/Measure__c.field-meta.xml
<CustomField>
    <fullName>Measure__c</fullName>
    <label>Measure</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coctail__c/Coctail__c.object-meta.xml
<CustomObject>
    <label>Cocktail</label>
    <nameField>
        <label>Coctail Recipe Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cocktails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Coctail__c/fields/Drink_External_Id__c.field-meta.xml
<CustomField>
    <fullName>Drink_External_Id__c</fullName>
    <externalId>true</externalId>
    <label>Drink External Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coctail__c/fields/Ingredient1__c.field-meta.xml
<CustomField>
    <fullName>Ingredient1__c</fullName>
    <label>Ingredient1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coctail__c/fields/Ingredient2__c.field-meta.xml
<CustomField>
    <fullName>Ingredient2__c</fullName>
    <label>Ingredient2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coctail__c/fields/Ingredient3__c.field-meta.xml
<CustomField>
    <fullName>Ingredient3__c</fullName>
    <label>Ingredient3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coctail__c/fields/Ingredient4__c.field-meta.xml
<CustomField>
    <fullName>Ingredient4__c</fullName>
    <label>Ingredient4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coctail__c/fields/Ingredient5__c.field-meta.xml
<CustomField>
    <fullName>Ingredient5__c</fullName>
    <label>Ingredient5</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coctail__c/fields/Measure1__c.field-meta.xml
<CustomField>
    <fullName>Measure1__c</fullName>
    <label>Measure1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coctail__c/fields/Measure2__c.field-meta.xml
<CustomField>
    <fullName>Measure2__c</fullName>
    <label>Measure2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coctail__c/fields/Measure3__c.field-meta.xml
<CustomField>
    <fullName>Measure3__c</fullName>
    <label>Measure3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coctail__c/fields/Measure4__c.field-meta.xml
<CustomField>
    <fullName>Measure4__c</fullName>
    <label>Measure4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coctail__c/fields/Measure5__c.field-meta.xml
<CustomField>
    <fullName>Measure5__c</fullName>
    <label>Measure5</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

.history/force-app/main/default/classes/CocktailRestServiceHandler_20230217173233.cls
public with sharing class CocktailRestServiceHandler {

    public void insertRecepies(list<Coctail__c> Cocktails) {

    List<Cocktail_Ingredients__c> CoctailsIngrUpload = new List<Cocktail_Ingredients__c>();

    //CocktailHelper coctailWrapper = new CocktailHelper();

    Schema.SObjectField externalId = Coctail__c.Fields.Drink_External_Id__c;

    //List<Coctail__c> dedupedCoctails =  coctailWrapper.removeDuplicateDrinks(Cocktails);

      /* Perform the upsert. In this case the unique identifier for the
         insert or update decision is the Salesforce record ID. If the
         record ID is null the row will be inserted, otherwise an update
         will be attempted. */

      List<Database.upsertResult> uResults = Database.upsert(Cocktails,externalId,false);
      //upsert Cocktails Drink_External_Id__c;

   list<Id> insertedIds = new list<Id>();

   for(Database.upsertResult c : uResults){
    if (c.isSuccess() && c.isCreated()){
      insertedIds.add(c.getId());
    }
   }

   List<Coctail__c> createdRecordList = [SELECT Id,Name,Ingredient1__c,Ingredient2__c,Ingredient3__c,Ingredient4__c,Ingredient5__c,
   Measure1__c,Measure2__c,Measure3__c,Measure4__c,Measure5__c FROM Coctail__c WHERE Id IN:insertedIds];

   map<Id,Coctail__c> createdRecordMap = new map<Id,Coctail__c>(createdRecordList);

   system.debug('List is ');
   system.debug(createdRecordList);
  system.debug(createdRecordMap);
  system.debug(createdRecordMap.values());


    for (Coctail__c c : createdRecordMap.values()) {

      for (Integer i = 1; i <= 5; i++) {
        if (!String.isBlank((String) c.get('Ingredient' + i + '__c'))) {
          Cocktail_Ingredients__c ci = new Cocktail_Ingredients__c(
            Name = (String) c.get('Ingredient' + i + '__c'),
            Measure__c = (String) c.get('Measure' + i + '__c'),
            Cocktail__c = c.Id,
            Drink_Ing_External_Id__c = c.Id +
              (String) c.get('Ingredient' + i + '__c')
          );
          CoctailsIngrUpload.add(ci);
          system.debug(ci);
        }
      }
    }

    system.debug(CoctailsIngrUpload);
    Database.upsert(CoctailsIngrUpload;


  }

  public list<Coctail__c> returnCocktailsFromAPI(String ingredient) {
    list<String> fetchDrinkIds = CocktailRestService.getCocktailsByIngr(
      ingredient
    );
    list<Coctail__c> CoctailList = new List<Coctail__c>();

    for (String drinkId : fetchDrinkIds) {
      CoctailList.addAll(CocktailRestService.getCocktailDetailsbyId(drinkId));
    }

    return CoctailList;
  }
}