force-app/main/default/objects/Cocktail_Ingredients__c/Cocktail_Ingredients__c.object-meta.xml
<CustomObject>
    <label>Cocktail Ingredient</label>
    <nameField>
        <label>Cocktail Ingredients Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cocktail Ingredients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Coctail__c/Coctail__c.object-meta.xml
<CustomObject>
    <label>Cocktail</label>
    <nameField>
        <label>Coctail Recipe Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cocktails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Coctail__c/fields/Drink_External_Id__c.field-meta.xml
<CustomField>
    <fullName>Drink_External_Id__c</fullName>
    <externalId>true</externalId>
    <label>Drink External Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coctail__c/fields/Instructions__c.field-meta.xml
<CustomField>
    <fullName>Instructions__c</fullName>
    <description>Drink preparation instruction</description>
    <label>Instructions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Coctail__c/fields/PictureURL__c.field-meta.xml
<CustomField>
    <fullName>PictureURL__c</fullName>
    <description>Cocktail picture</description>
    <label>Picture URL</label>
    <type>Url</type>
</CustomField>

.history/force-app/main/default/classes/CocktailRestService_20230214121434.cls
public with sharing class CocktailRestService {
  public static void getCocktailById(String CoctailId) {
    Http http = new Http();
    HttpRequest request = new HttpRequest();
    String requestBody = '/api/json/v1/1/lookup.php?i=' + CoctailId;
    request.setEndpoint('callout:CocktailDB' + requestBody);
    request.setMethod('GET');
    HttpResponse response = http.send(request);
    // If the request is successful, parse the JSON response.
    if (response.getStatusCode() == 200) {
      CocktailsJSON2APEX cocktailList = CocktailsJSON2APEX.parse(
        response.getBody()
      );

      list<Coctail__c> CoctailsToUpload = new List<Coctail__c>();
      for (CocktailsJSON2APEX.Drink d : cocktailList.drinks) {
        Coctail__c c = new Coctail__c(
          Name = d.strDrink,
          Drink_External_Id__c = d.idDrink,
          PictureURL__c = d.strImageSource,
          Instructions__c = d.strInstructions
        );
        CoctailsToUpload.add(c);
      }
    }
  }

  public static void getCocktailsByIngr(String ingredient) {
    Http http = new Http();
    HttpRequest request = new HttpRequest();
    String requestBody = '/api/json/v1/1/filter.php?i=' + ingredient;
    request.setEndpoint('callout:CocktailDB' + requestBody);
    request.setMethod('GET');
    HttpResponse response = http.send(request);
    // If the request is successful, parse the JSON response.
    if (response.getStatusCode() == 200) {
      CoctailsByIngredientsJSON2APEX cocktailList = CoctailsByIngredientsJSON2APEX.parse(
        response.getBody()
      );
      list<Coctail__c> CoctailsToUpload = new List<Coctail__c>();
      list<Cocktail_Ingredients__c> CoctailsIngrUpload = new List<Cocktail_Ingredients__c>();



    }
  }
}