force-app/main/default/objects/Cocktail_Ingredients__c/Cocktail_Ingredients__c.object-meta.xml
<CustomObject>
    <label>Cocktail Ingredient</label>
    <nameField>
        <label>Cocktail Ingredients Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cocktail Ingredients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cocktail_Ingredients__c/fields/Cocktail__c.field-meta.xml
<CustomField>
    <fullName>Cocktail__c</fullName>
    <label>Cocktail</label>
    <referenceTo>Coctail__c</referenceTo>
    <relationshipLabel>Cocktail Ingredients</relationshipLabel>
    <relationshipName>Cocktail_Ingredients</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cocktail_Ingredients__c/fields/Drink_Ing_External_Id__c.field-meta.xml
<CustomField>
    <fullName>Drink_Ing_External_Id__c</fullName>
    <externalId>true</externalId>
    <label>Drink_Ing_External_Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cocktail_Ingredients__c/fields/Measure__c.field-meta.xml
<CustomField>
    <fullName>Measure__c</fullName>
    <label>Measure</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coctail__c/Coctail__c.object-meta.xml
<CustomObject>
    <label>Cocktail</label>
    <nameField>
        <label>Coctail Recipe Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cocktails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

.history/force-app/main/default/classes/CocktailRestServiceHandler_20230214160414.cls
public with sharing class CocktailRestServiceHandler {

    public void insertRecepies(list<Coctail__c> Cocktails) {

    List<Cocktail_Ingredients__c> CoctailsIngrUpload = new List<Cocktail_Ingredients__c>();

    

    for (Coctail__c c : Cocktails) {

      for (Integer i = 1; i <= 5; i++) {
        if (!String.isBlank((String) c.get('Ingredient' + i + '__c'))) {
          Cocktail_Ingredients__c ci = new Cocktail_Ingredients__c(
            Name = (String) c.get('Ingredient' + i + '__c'),
            Measure__c = (String) c.get('Measure' + i + '__c'),
            Cocktail__c = c.Id,
            Drink_Ing_External_Id__c = c.id +
              (String) c.get('Ingredient' + i + '__c')
          );
          CoctailsIngrUpload.add(ci);
        }
      }
    }
  }



  private list<Coctail__c> returnCocktailsFromAPI(String ingredient) {
    list<String> fetchDrinkIds = CocktailRestService.getCocktailsByIngr(
      ingredient
    );
    list<Coctail__c> CoctailList = new List<Coctail__c>();

    for (String drinkId : fetchDrinkIds) {
      CoctailList.addAll(CocktailRestService.getCocktailById(drinkId));
    }

    return CoctailList;
  }
}