force-app/main/default/objects/Cocktail_Ingredients__c/Cocktail_Ingredients__c.object-meta.xml
<CustomObject>
    <label>Cocktail Ingredient</label>
    <nameField>
        <label>Cocktail Ingredients Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cocktail Ingredients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cocktail_Ingredients__c/fields/Cocktail__c.field-meta.xml
<CustomField>
    <fullName>Cocktail__c</fullName>
    <label>Cocktail</label>
    <referenceTo>Coctail__c</referenceTo>
    <relationshipLabel>Cocktail Ingredients</relationshipLabel>
    <relationshipName>Cocktail_Ingredients</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cocktail_Ingredients__c/fields/Drink_Ing_External_Id__c.field-meta.xml
<CustomField>
    <fullName>Drink_Ing_External_Id__c</fullName>
    <externalId>true</externalId>
    <label>Drink_Ing_External_Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cocktail_Ingredients__c/fields/Measure__c.field-meta.xml
<CustomField>
    <fullName>Measure__c</fullName>
    <label>Measure</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coctail__c/Coctail__c.object-meta.xml
<CustomObject>
    <label>Cocktail</label>
    <nameField>
        <label>Coctail Recipe Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cocktails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Coctail__c/fields/Drink_External_Id__c.field-meta.xml
<CustomField>
    <fullName>Drink_External_Id__c</fullName>
    <externalId>true</externalId>
    <label>Drink External Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coctail__c/fields/Ingredient1__c.field-meta.xml
<CustomField>
    <fullName>Ingredient1__c</fullName>
    <label>Ingredient1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coctail__c/fields/Ingredient2__c.field-meta.xml
<CustomField>
    <fullName>Ingredient2__c</fullName>
    <label>Ingredient2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coctail__c/fields/Ingredient3__c.field-meta.xml
<CustomField>
    <fullName>Ingredient3__c</fullName>
    <label>Ingredient3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coctail__c/fields/Ingredient4__c.field-meta.xml
<CustomField>
    <fullName>Ingredient4__c</fullName>
    <label>Ingredient4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coctail__c/fields/Ingredient5__c.field-meta.xml
<CustomField>
    <fullName>Ingredient5__c</fullName>
    <label>Ingredient5</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coctail__c/fields/Instructions__c.field-meta.xml
<CustomField>
    <fullName>Instructions__c</fullName>
    <description>Drink preparation instruction</description>
    <label>Instructions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Coctail__c/fields/Measure1__c.field-meta.xml
<CustomField>
    <fullName>Measure1__c</fullName>
    <label>Measure1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coctail__c/fields/Measure2__c.field-meta.xml
<CustomField>
    <fullName>Measure2__c</fullName>
    <label>Measure2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coctail__c/fields/Measure3__c.field-meta.xml
<CustomField>
    <fullName>Measure3__c</fullName>
    <label>Measure3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coctail__c/fields/Measure4__c.field-meta.xml
<CustomField>
    <fullName>Measure4__c</fullName>
    <label>Measure4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coctail__c/fields/Measure5__c.field-meta.xml
<CustomField>
    <fullName>Measure5__c</fullName>
    <label>Measure5</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coctail__c/fields/PictureURL__c.field-meta.xml
<CustomField>
    <fullName>PictureURL__c</fullName>
    <description>Cocktail picture</description>
    <label>Picture URL</label>
    <type>Url</type>
</CustomField>

.history/force-app/main/default/classes/CocktailRestService_20230214123640.cls
public with sharing class CocktailRestService {
  public static void getCocktailById(String CoctailId) {
    Http http = new Http();
    HttpRequest request = new HttpRequest();
    String requestBody = '/api/json/v1/1/lookup.php?i=' + CoctailId;
    request.setEndpoint('callout:CocktailDB' + requestBody);
    request.setMethod('GET');
    HttpResponse response = http.send(request);
    // If the request is successful, parse the JSON response.
    if (response.getStatusCode() == 200) {
      CocktailsJSON2APEX cocktailList = CocktailsJSON2APEX.parse(
        response.getBody()
      );

      list<Coctail__c> CoctailsToUpload = new List<Coctail__c>();
      for (CocktailsJSON2APEX.Drink d : cocktailList.drinks) {
        Coctail__c c = new Coctail__c(
          Name = d.strDrink,
          Drink_External_Id__c = d.idDrink,
          PictureURL__c = d.strImageSource,
          Instructions__c = d.strInstructions
        );
        CoctailsToUpload.add(c);
      }
    }
  }

  public static void getCocktailsByIngr(String ingredient) {
    Http http = new Http();
    HttpRequest request = new HttpRequest();
    String requestBody = '/api/json/v1/1/filter.php?i=' + ingredient;
    request.setEndpoint('callout:CocktailDB' + requestBody);
    request.setMethod('GET');
    HttpResponse response = http.send(request);

    // I NEED TO PULL COCTAIL BY CoctailsByIngredientsJSON2APEX FIRST AND THEN CocktailsJSON2APEX !!!

    // If the request is successful, parse the JSON response.
    if (response.getStatusCode() == 200) {
      CoctailsByIngredientsJSON2APEX cocktailListbyId = CoctailsByIngredientsJSON2APEX.parse(
        response.getBody()
      );

      for(CoctailsByIngredientsJSON2APEX.Drink d : cocktailListbyId.drink){

        
      }


      list<Coctail__c> CoctailsToUpload = new List<Coctail__c>();
      list<Cocktail_Ingredients__c> CoctailsIngrUpload = new List<Cocktail_Ingredients__c>();

      for (CocktailsJSON2APEX.Drink d : cocktailList.drinks) {

        Coctail__c c = new Coctail__c(
        Name = d.strDrink,
        Drink_External_Id__c = d.idDrink,
        PictureURL__c = d.strImageSource,
        Instructions__c  = d.strInstructions,
        Ingredient1__c = d.strIngredient1,
        Ingredient2__c = d.strIngredient2,
        Ingredient3__c = d.strIngredient3,
        Ingredient4__c = d.strIngredient4,
        Ingredient5__c = d.strIngredient5,
        Measure1__c = d.strMeasure1,
        Measure2__c = d.strMeasure2,
        Measure3__c = d.strMeasure3,
        Measure4__c = d.strMeasure4,
        Measure5__c = d.strMeasure5

        );
        CoctailsToUpload.add(c);

           for(Integer i = 1 ;i <=5; i++){

               if(!String.isBlank((String)c.get('Ingredient'+ i +'__c'))){

				Cocktail_Ingredients__c ci = new Cocktail_Ingredients__c(

				  Name = (String)c.get('Ingredient'+ i +'__c'),
                   Measure__c = (String)c.get('Measure'+ i +'__c'),
                    Cocktail__c = c.Id,
                    Drink_Ing_External_Id__c = c.id + (String)c.get('Ingredient'+ i +'__c')

                );
                    CoctailsIngrUpload.add(ci);
               }
        }

    }

    upsert CoctailsToUpload Drink_External_Id__c;
    upsert CoctailsIngrUpload Drink_Ing_External_Id__c;
  }


}
}