force-app/main/default/objects/Coctail__c/Coctail__c.object-meta.xml
<CustomObject>
    <label>Cocktail</label>
    <nameField>
        <label>Coctail Recipe Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cocktails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Coctail__c/fields/Drink_External_Id__c.field-meta.xml
<CustomField>
    <fullName>Drink_External_Id__c</fullName>
    <externalId>true</externalId>
    <label>Drink External Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coctail__c/fields/Ingredient1__c.field-meta.xml
<CustomField>
    <fullName>Ingredient1__c</fullName>
    <label>Ingredient1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coctail__c/fields/Ingredient2__c.field-meta.xml
<CustomField>
    <fullName>Ingredient2__c</fullName>
    <label>Ingredient2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coctail__c/fields/Ingredient3__c.field-meta.xml
<CustomField>
    <fullName>Ingredient3__c</fullName>
    <label>Ingredient3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coctail__c/fields/Ingredient4__c.field-meta.xml
<CustomField>
    <fullName>Ingredient4__c</fullName>
    <label>Ingredient4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coctail__c/fields/Ingredient5__c.field-meta.xml
<CustomField>
    <fullName>Ingredient5__c</fullName>
    <label>Ingredient5</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coctail__c/fields/Instructions__c.field-meta.xml
<CustomField>
    <fullName>Instructions__c</fullName>
    <description>Drink preparation instruction</description>
    <label>Instructions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Coctail__c/fields/Measure1__c.field-meta.xml
<CustomField>
    <fullName>Measure1__c</fullName>
    <label>Measure1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coctail__c/fields/Measure2__c.field-meta.xml
<CustomField>
    <fullName>Measure2__c</fullName>
    <label>Measure2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coctail__c/fields/Measure3__c.field-meta.xml
<CustomField>
    <fullName>Measure3__c</fullName>
    <label>Measure3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coctail__c/fields/Measure4__c.field-meta.xml
<CustomField>
    <fullName>Measure4__c</fullName>
    <label>Measure4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coctail__c/fields/Measure5__c.field-meta.xml
<CustomField>
    <fullName>Measure5__c</fullName>
    <label>Measure5</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coctail__c/fields/PictureURL__c.field-meta.xml
<CustomField>
    <fullName>PictureURL__c</fullName>
    <description>Cocktail picture</description>
    <label>Picture URL</label>
    <type>Url</type>
</CustomField>

.history/force-app/main/default/classes/CocktailRestService_20230227164546.cls
public with sharing class CocktailRestService {
  // Fetch drink Details from external API

  public static list<Coctail__c> getCocktailDetailsbyId(String CoctailId) {
    Http http = new Http();
    HttpRequest request = new HttpRequest();
    String requestBody = '/api/json/v1/1/lookup.php?i=' + CoctailId;
    request.setEndpoint('callout:CocktailDB' + requestBody);
    request.setMethod('GET');
    HttpResponse response = http.send(request);
    list<Coctail__c> CoctailsToUpload = new List<Coctail__c>();
    // If the request is successful, parse the JSON response.
    if (response.getStatusCode() == 200) {
      CocktailsJSON2APEX cocktailList = CocktailsJSON2APEX.parse(
        response.getBody()
      );

      for (CocktailsJSON2APEX.Drink d : cocktailList.drinks) {
        Coctail__c c = new Coctail__c(
          Name = d.strDrink,
          Drink_External_Id__c = d.idDrink,
          PictureURL__c = d.strDrinkThumb,
          Instructions__c = d.strInstructions,
          Ingredient1__c = d.strIngredient1,
          Ingredient2__c = d.strIngredient2,
          Ingredient3__c = d.strIngredient3,
          Ingredient4__c = d.strIngredient4,
          Ingredient5__c = d.strIngredient5,
          Measure1__c = d.strMeasure1,
          Measure2__c = d.strMeasure2,
          Measure3__c = d.strMeasure3,
          Measure4__c = d.strMeasure4,
          Measure5__c = d.strMeasure5
        );
        CoctailsToUpload.add(c);
      }
    }

    return CoctailsToUpload;
  }

  // Fetch list of drinks with specific ingredenits from external API

  public static list<String> getCocktailsByIngr(String ingredient) {
    Http http = new Http();
    HttpRequest request = new HttpRequest();
    String requestBody = '/api/json/v1/1/filter.php?i=' + ingredient;
    request.setEndpoint('callout:CocktailDB' + requestBody);
    request.setMethod('GET');
    HttpResponse response = http.send(request);

    list<String> DrinkIds = new List<String>();

    if (response.getStatusCode() == 200) {
      CoctailsByIngredientsJSON2APEX cocktailList = CoctailsByIngredientsJSON2APEX.parse(
        response.getBody()
      );

      for (CoctailsByIngredientsJSON2APEX.Drink d : cocktailList.drinks) {
        DrinkIds.add(d.IdDrink);
      }
    }
    return DrinkIds;
  }

  public static list<Coctail__c> getCocktailsByName(String cocktailName) {
    Http http = new Http();
    HttpRequest request = new HttpRequest();
    String requestBody = '/api/json/v1/1/search.php?i=' + cocktailName;
    request.setEndpoint('callout:CocktailDB' + requestBody);
    request.setMethod('GET');
    HttpResponse response = http.send(request);

    list<Coctail__c> CoctailsToUpload = new List<Coctail__c>();



    }

}