force-app/main/default/objects/Coctail__c/Coctail__c.object-meta.xml
<CustomObject>
    <label>Cocktail</label>
    <nameField>
        <label>Coctail Recipe Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cocktails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Coctail__c/fields/PictureURL__c.field-meta.xml
<CustomField>
    <fullName>PictureURL__c</fullName>
    <description>Cocktail picture</description>
    <label>Picture URL</label>
    <type>Url</type>
</CustomField>

.history/force-app/main/default/classes/CocktailTriggerHandler_20230217181208.cls
public with sharing class CocktailTriggerHandler {

 public static void beforeUpdateRemoveDuplicate(list<Coctail__c> newList,map<Id, Coctail__c> oldContactsMap) {
    for (Coctail__c c : newList) {
      if (c.PictureURL__c == oldContactsMap.get(c.id).PictureURL__c) {
        c.AddError('Drink URL has not changed');
      }
    }
  }
}


trigger UpdateTriggerSample_tgr on Lead (after update) { Lead NewLead = trigger.new[0]; Lead OldLead = trigger.old[0]; Lead LeadObject = new Lead(); // This takes all available fields from the required object.
     Schema.SObjectType objType = Coctail__c.getSObjectType();
     
     Map<String, Schema.SObjectField> M = Schema.SObjectType.Coctail__c.fields.getMap();
     
     for (String str : M.keyset()) { try { System.debug('Field name: '+str +'. New value: ' + NewLead.get(str) +'. Old value: '+OldLead.get(str)); if(NewLead.get(str) != OldLead.get(str)){ system.debug('******The value has changed!!!! '); // here goes more code } } catch (Exception e) { System.debug('Error: ' + e); } } }