force-app/main/default/objects/Coctail__c/Coctail__c.object-meta.xml
<CustomObject>
    <label>Cocktail</label>
    <nameField>
        <label>Coctail Recipe Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cocktails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Coctail__c/fields/Ingredient1__c.field-meta.xml
<CustomField>
    <fullName>Ingredient1__c</fullName>
    <label>Ingredient1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

.history/force-app/main/default/classes/CocktailLWCHandler_20230220141839.cls
public with sharing class CocktailLWCHandler {


    @AuraEnabled(cacheable = true)
    public static List<Coctail__c> getExisitngCocktailByIngredient(String inggredient){

        List<Coctail__c> cocktails = new List<Coctail__c>();
        if(String.isEmpty(inggredient))

        cocktails = [Select Id,Name from Coctail__c WHERE Ingredient1__c LIKE '%inggredient%'];

        return cocktails;


    }

    @AuraEnabled(cacheable = true)
    public static List<Coctail__c> getExistingCocktailByName(){


    }

}