force-app/main/default/objects/Coctail__c/Coctail__c.object-meta.xml
<CustomObject>
    <label>Cocktail</label>
    <nameField>
        <label>Coctail Recipe Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cocktails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Coctail__c/fields/No_Ingredients__c.field-meta.xml
<CustomField>
    <fullName>No_Ingredients__c</fullName>
    <label>No of Ingredients</label>
    <summaryForeignKey>Cocktail_Ingredients__c.Cocktail__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Coctail__c/fields/PictureURL__c.field-meta.xml
<CustomField>
    <fullName>PictureURL__c</fullName>
    <description>Cocktail picture</description>
    <label>Picture URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/CocktailTriggerHandler.cls
public with sharing class CocktailTriggerHandler {

 public static void beforeUpdateRemoveDuplicate(list<Coctail__c> newList,map<Id, Coctail__c> oldContactsMap) {
    for (Coctail__c c : newList) {
      if (c.PictureURL__c == oldContactsMap.get(c.id).PictureURL__c && c.No_Ingredients__c == oldContactsMap.get(c.id).No_Ingredients__c) {
        c.AddError('This record has not changed');
      }
    }
  }
}