force-app/main/default/objects/Coctail__c/Coctail__c.object-meta.xml
<CustomObject>
    <label>Cocktail</label>
    <nameField>
        <label>Coctail Recipe Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cocktails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Coctail__c/fields/Drink_External_Id__c.field-meta.xml
<CustomField>
    <fullName>Drink_External_Id__c</fullName>
    <externalId>true</externalId>
    <label>Drink External Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

.history/force-app/main/default/classes/CocktailRestService_20230213200430.cls
public with sharing class CocktailRestService {


    public static void getCocktailByName(String CoctailName) {
    Http http = new Http();
    HttpRequest request = new HttpRequest();
    String requestBody = '/api/json/v1/1/search.php?s='+ CoctailName;
    request.setEndpoint(
      'callout:CocktailDB' + requestBody
    );
    request.setMethod('GET');
    HttpResponse response = http.send(request);
    // If the request is successful, parse the JSON response.
    if (response.getStatusCode() == 200) {
      CocktailsJSON2APEX cocktailList = CocktailsJSON2APEX.parse(
        response.getBody()
      );

      system.debug(cocktailList);

      for(CocktailsJSON2APEX.Drink d : cocktailList.drinks) {
        system.debug(d);
      }
    }
  }


    public static void getCocktailsByIngr(String ingredient) {
    Http http = new Http();
    HttpRequest request = new HttpRequest();
    String requestBody = '/api/json/v1/1/search.php?i='+ ingredient;
    request.setEndpoint(
      'callout:CocktailDB' + requestBody
    );
    request.setMethod('GET');
    HttpResponse response = http.send(request);
    // If the request is successful, parse the JSON response.
    if (response.getStatusCode() == 200) {
      CoctailsByIngredientsJSON2APEX cocktailList = CoctailsByIngredientsJSON2APEX.parse(
        response.getBody()
      );

      List<Id> drinkIds = new list<Id>();

      for(CoctailsByIngredientsJSON2APEX.Drink d : cocktailList.drinks){

        drinkIds.add(d.idDrink);

      }

      list<Id> existingRecord = new list<Id>();
      
      
      [SELECT Drink_External_Id__c from Coctail__c WHERE Drink_External_Id__c IN:drinkIds];

      for(CoctailsByIngredientsJSON2APEX.Drink d : cocktailList.drinks){

        if(existingRecord.contains(d.idDrink)){

          system.debug(d);
        }

     }


    }
  }

}