force-app/main/default/objects/Coctail__c/Coctail__c.object-meta.xml
<CustomObject>
    <label>Cocktail</label>
    <nameField>
        <label>Coctail Recipe Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cocktails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Coctail__c/fields/Ingredient1__c.field-meta.xml
<CustomField>
    <fullName>Ingredient1__c</fullName>
    <label>Ingredient1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coctail__c/fields/Ingredient2__c.field-meta.xml
<CustomField>
    <fullName>Ingredient2__c</fullName>
    <label>Ingredient2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coctail__c/fields/Ingredient3__c.field-meta.xml
<CustomField>
    <fullName>Ingredient3__c</fullName>
    <label>Ingredient3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coctail__c/fields/Ingredient4__c.field-meta.xml
<CustomField>
    <fullName>Ingredient4__c</fullName>
    <label>Ingredient4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coctail__c/fields/Ingredient5__c.field-meta.xml
<CustomField>
    <fullName>Ingredient5__c</fullName>
    <label>Ingredient5</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coctail__c/fields/PictureURL__c.field-meta.xml
<CustomField>
    <fullName>PictureURL__c</fullName>
    <description>Cocktail picture</description>
    <label>Picture URL</label>
    <type>Url</type>
</CustomField>

.history/force-app/main/default/classes/CocktailService_20230220174743.cls
public with sharing class CocktailService {



    public List<Coctail__c> getCocktailsbyIngredient(String ingredient){

         List<Coctail__c> cocktails = new List<Coctail__c>();
        if(String.isEmpty(ingredient)){

        cocktails = [Select Id,Name,PictureURL__c,Ingredient1__c,Ingredient2__c,Ingredient3,Ingredient4,Ingredient5  from Coctail__c Order by Name];
        }
        else{

        String filterVar = ingredient + '%';

        cocktails = [Select Id,Name,PictureURL__c ,Ingredient1__c,Ingredient2__c,Ingredient3,Ingredient4,Ingredient5 from Coctail__c WHERE Ingredient1__c LIKE:filterVar OR Ingredient2__c LIKE:filterVar OR Ingredient3__c LIKE:filterVar OR Ingredient4__c LIKE:filterVar OR Ingredient5__c LIKE:filterVar];

        }

        return cocktails;

    }

    public List<Coctail__c> getCocktailsbyName(String cocktailName){

         List<Coctail__c> cocktails = new List<Coctail__c>();
        if(String.isEmpty(cocktailName)){

        cocktails = [Select Id,PictureURL__c ,Name ,Ingredient1__c,Ingredient2__c,Ingredient3__c,Ingredient4__c,Ingredient5 from Coctail__c Order by Name];
        }
        else{

        String filterVar = cocktailName + '%';

        cocktails = [Select Id,Name,PictureURL__c ,Ingredient1__c,Ingredient2__c,Ingredient3,Ingredient4,Ingredient5 from Coctail__c WHERE Name LIKE: filterVar];

        }

        return cocktails;

    }


}