force-app/main/default/objects/Coctail__c/Coctail__c.object-meta.xml
<CustomObject>
    <label>Cocktail</label>
    <nameField>
        <label>Coctail Recipe Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cocktails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Coctail__c/fields/Drink_External_Id__c.field-meta.xml
<CustomField>
    <fullName>Drink_External_Id__c</fullName>
    <externalId>true</externalId>
    <label>Drink External Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

.history/force-app/main/default/classes/CocktailController_20230214165619.cls
public with sharing class CocktailController {

    public List<Coctail__c> removeDuplicateDrinks(list<Coctail__c> coctails){

        

        List<Coctail__c> drinks = [Select Id,Name,Drink_External_Id__c from Coctail__c where Drink_External_Id__c IN: returnDrinkExternalIds(coctails)];

       for(Coctail__c c : coctails){

        if(drinks.contains()){

            system.debug('duplicate' + c.Id);
        }
       }

    }


    public list<String> returnDrinkExternalIds(list<Coctail__c> coctails){

        list<String> cocktailExternalIds = new list<String>();

        for(Coctail__c c : coctails){
           cocktailExternalIds.add(c.drinkExternalIds);

        }

        return cocktailExternalIds;


    }

}