force-app/main/default/objects/Coctail__c/Coctail__c.object-meta.xml
<CustomObject>
    <label>Cocktail</label>
    <nameField>
        <label>Coctail Recipe Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cocktails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Coctail__c/fields/PictureURL__c.field-meta.xml
<CustomField>
    <fullName>PictureURL__c</fullName>
    <description>Cocktail picture</description>
    <label>Picture URL</label>
    <type>Url</type>
</CustomField>

.history/force-app/main/default/classes/CocktailTriggerHandler_20230217152945.cls
public with sharing class CocktailTriggerHandler {

    public void beforeUpdateRemoveDuplicate(map<Id,Coctail__c> newContactsMap){

        List<Coctail__c> cList = new list <Coctail__c>();

        for(Coctail__c c : newContactsMap.values()){

            if(c.PictureURL__c === newContactsMap.get(c.id).PictureURL__c){

                c.AddError(['Drink URL has not changed']);

            }

        }




    }
}